<h2> Basic Artificial Neural Network</h2>

<p>Lets make an ANN that will show whether a student will perform good or bad based on that students habits</p>

In [44]:
# Importing the required libraries
import numpy as np
# yeah thats it

<p>The input features will be a rating from 0 to 1 = poor to good in a sequence: "self study, timepass, sleep, performance in class"</p>


In [70]:
# input
X = np.array([[1,0,1,1],
              [0,1,1,0],
              [1,1,1,1]])

In [71]:
# output
y = np.array([[1],
             [0],
             [1]])

In [47]:
# activation function
def sigmoid(x,deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [72]:
# initialization model variables
epoch = 500
lr = 0.1
inputlayer_neurons = X.shape[1] # number of features in the data
hiddenlayer_neurons = 3 # number of hidden neurons
output_neurons = y.shape[1] # number of output neurons

In [73]:
# initialization of weight and bias
w_hidden = np.random.uniform(size = (inputlayer_neurons, hiddenlayer_neurons))
b_hidden = np.random.uniform(size = (1, hiddenlayer_neurons))
w_output = np.random.uniform(size =(hiddenlayer_neurons, output_neurons))
b_output = np.random.uniform(size = (1, output_neurons))

In [81]:
# training the model
for i in range(1000):
    # Forward propagation
    hiddenlayer_input = np.dot(X, w_hidden) + b_hidden
    hiddenlayer_activation = sigmoid(hiddenlayer_input, deriv = False)
    outputlayer_input = np.dot(hiddenlayer_activation, w_output) + b_out
    output = sigmoid(outputlayer_input, deriv = False)
    
    # Back Propagation
    Error = y - output
    slope_outputlayer = sigmoid(output, deriv = True)
    slope_hiddenlayer = sigmoid(hiddenlayer_activation, deriv = True)
    delta_output = Error * slope_outputlayer 
    Error_hiddenlayer = np.dot(delta_output, w_output.T)
    delta_hiddenlayer = Error_hiddenlayer * slope_hiddenlayer
    w_output = w_output + np.dot(hiddenlayer_activation.T, delta_output) * lr
    b_output = b_output + np.sum(delta_output, axis = 0, keepdims = True) * lr
    w_hidden = w_hidden + np.dot(X.T, delta_hiddenlayer) * lr
    b_hidden = b_hidden + np.sum(delta_hiddenlayer, axis = 0, keepdims = True) *lr
    if i % 100 == 0:
        print(i)

print(output)
    
  

0
100
200
300
400
500
600
700
800
900
[[0.96293521 0.98344375 0.96012676]
 [0.93790918 0.05420234 0.92180073]
 [0.98591081 0.92369651 0.98204279]]
[[0.94064756]
 [0.11971139]
 [0.9164    ]]


In [95]:
test = [[0.1,0.9,0.9,0.2]]
hiddenlayer_input = np.dot(test, w_hidden) + b_hidden
hiddenlayer_activation = sigmoid(hiddenlayer_input, deriv = False)
outputlayer_input = np.dot(hiddenlayer_activation, w_output) + b_out
output = sigmoid(outputlayer_input, deriv = False)
if output > 0.5:
    print("He's doin good")
else:
    print("Bro wake up")

Bro wake up
